name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Docker
      run: |
        sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    - name: Install Docker Compose
      run: |
        sudo wget "https://github.com/docker/compose/releases/download/v2.33.1/docker-compose-linux-x86_64" -O /usr/bin/docker-compose
        sudo chmod +x /usr/bin/docker-compose

    - name: Build and Release
      run: make build_docker

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: StealthIMFileStorage.docker.zst
        path: ./bin/StealthIMFileStorage.docker.zst

  upload-package:
    runs-on: ubuntu-latest
    needs: release
    permissions:
      packages: write

    steps:
    - name: Download File
      uses: actions/download-artifact@v4
      with:
        name: StealthIMFileStorage.docker.zst

    - name: Unpack File
      run: |
        sudo apt-get update
        sudo apt-get install -y zstd
        zstd -d StealthIMFileStorage.docker.zst

    - name: Load Docker image
      run: docker load -i StealthIMFileStorage.docker

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PKGTOKEN }}

    - name: Tag and push Docker image
      run: |
        docker tag $(docker images -q | head -n 1) ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')/$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')/stealthimfilestorage-app:latest
        docker push ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')/$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')/stealthimfilestorage-app:latest
